apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: learningcenter
spec:
  portal:
    ingress:
      hostname: learningcenter
    registration:
      type: anonymous
    reserved: 2
    sessions:
      maximum: 5
    updates:
      workshop: true
  workshops:
  - name: lab-markdown-sample
    capacity: 2
    expires: 60m
    orphaned: 15m